name: seurat_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.44=h4bf12b8_0
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.14.1=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_3
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_3
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=h5888daf_0
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_3
  - harfbuzz=11.2.1=h3beb420_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_0
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=15.1.0=h4c094af_103
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libpng=1.6.50=h943b412_0
  - libsanitizer=15.1.0=h97b714f_3
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_103
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pandoc=3.7.0.2=ha770c72_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.45=hc749103_0
  - pixman=0.46.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - r-abind=1.4_5=r43hc72bb7e_1006
  - r-askpass=1.2.1=r43h2b5f3a1_0
  - r-base=4.3.3=h65010dc_18
  - r-base64enc=0.1_3=r43hb1dbf0f_1007
  - r-bh=1.87.0_1=r43hc72bb7e_0
  - r-bitops=1.0_9=r43h2b5f3a1_0
  - r-bslib=0.9.0=r43hc72bb7e_0
  - r-cachem=1.1.0=r43hb1dbf0f_1
  - r-catools=1.18.3=r43h93ab643_0
  - r-cli=3.6.5=r43h93ab643_0
  - r-cluster=2.1.8.1=r43hb67ce94_0
  - r-codetools=0.2_20=r43hc72bb7e_1
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-commonmark=2.0.0=r43h2b5f3a1_0
  - r-cowplot=1.2.0=r43hc72bb7e_1
  - r-cpp11=0.5.2=r43h785f33e_1
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-crosstalk=1.2.1=r43hc72bb7e_1
  - r-curl=6.4.0=r43h10955f1_1
  - r-data.table=1.17.8=r43h1c8cec4_0
  - r-deldir=2.0_4=r43hbcb9c34_1
  - r-digest=0.6.37=r43h0d4f4ea_0
  - r-dotcall64=1.2=r43hb67ce94_0
  - r-dplyr=1.1.4=r43h0d4f4ea_1
  - r-dqrng=0.3.2=r43h0d4f4ea_1
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-evaluate=1.0.4=r43hc72bb7e_0
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-fastdummies=1.7.5=r43hc72bb7e_0
  - r-fastmap=1.2.0=r43ha18555a_1
  - r-fitdistrplus=1.2_4=r43hc72bb7e_0
  - r-fnn=1.1.4.1=r43h3697838_1
  - r-fontawesome=0.5.3=r43hc72bb7e_0
  - r-fs=1.6.6=r43h93ab643_0
  - r-future=1.67.0=r43h785f33e_0
  - r-future.apply=1.20.0=r43hc72bb7e_0
  - r-generics=0.1.4=r43hc72bb7e_0
  - r-ggplot2=3.5.2=r43hc72bb7e_0
  - r-ggrepel=0.9.6=r43h3697838_1
  - r-ggridges=0.5.6=r43hc72bb7e_1
  - r-globals=0.18.0=r43hc72bb7e_0
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-goftest=1.2_3=r43hb1dbf0f_3
  - r-gplots=3.2.0=r43hc72bb7e_0
  - r-gridextra=2.3=r43hc72bb7e_1006
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-gtools=3.9.5=r43hb1dbf0f_1
  - r-here=1.0.1=r43hc72bb7e_3
  - r-highr=0.11=r43hc72bb7e_1
  - r-htmltools=0.5.8.1=r43ha18555a_1
  - r-htmlwidgets=1.6.4=r43h785f33e_3
  - r-httpuv=1.6.15=r43ha18555a_1
  - r-httr=1.4.7=r43hc72bb7e_1
  - r-ica=1.0_3=r43hc72bb7e_3
  - r-igraph=2.1.4=r43hadbbdbc_0
  - r-irlba=2.3.5.1=r43h0d28552_3
  - r-isoband=0.2.7=r43ha18555a_3
  - r-jquerylib=0.1.4=r43hc72bb7e_3
  - r-jsonlite=2.0.0=r43h2b5f3a1_0
  - r-kernsmooth=2.23_26=r43h8461fee_0
  - r-knitr=1.50=r43hc72bb7e_0
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-later=1.4.2=r43h3697838_1
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-lazyeval=0.2.2=r43hb1dbf0f_5
  - r-leidenbase=0.1.32=r43he61314c_0
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-listenv=0.9.1=r43hc72bb7e_1
  - r-lmtest=0.9_40=r43hbcb9c34_3
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_5=r43he966344_1
  - r-matrixstats=1.5.0=r43h2b5f3a1_0
  - r-memoise=2.0.1=r43hc72bb7e_3
  - r-mgcv=1.9_3=r43h2ae2be5_0
  - r-mime=0.13=r43h2b5f3a1_0
  - r-miniui=0.1.2=r43hc72bb7e_0
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-nlme=3.1_168=r43hb67ce94_0
  - r-openssl=2.3.3=r43he8289e2_0
  - r-parallelly=1.45.1=r43h54b55ab_0
  - r-patchwork=1.3.1=r43hc72bb7e_0
  - r-pbapply=1.7_4=r43hc72bb7e_0
  - r-pillar=1.11.0=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-plotly=4.10.2=r43h6115d3f_0
  - r-plyr=1.8.9=r43h3697838_2
  - r-png=0.1_8=r43h21f035c_2
  - r-polyclip=1.10_7=r43h0d4f4ea_0
  - r-progressr=0.15.1=r43hc72bb7e_0
  - r-promises=1.3.3=r43h3697838_0
  - r-purrr=1.1.0=r43h54b55ab_0
  - r-r6=2.6.1=r43hc72bb7e_0
  - r-rann=2.6.2=r43h93ab643_0
  - r-rappdirs=0.3.3=r43hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-rcpp=1.1.0=r43h93ab643_0
  - r-rcppannoy=0.0.22=r43ha18555a_1
  - r-rcpparmadillo=14.6.0_1=r43h3704496_0
  - r-rcppeigen=0.3.4.0.2=r43hb79369c_0
  - r-rcpphnsw=0.6.0=r43h0d4f4ea_1
  - r-rcppprogress=0.4.2=r43hc72bb7e_4
  - r-rcpptoml=0.2.3=r43h93ab643_0
  - r-reshape2=1.4.4=r43h0d4f4ea_4
  - r-reticulate=1.43.0=r43h3697838_0
  - r-rlang=1.1.6=r43h93ab643_0
  - r-rmarkdown=2.29=r43hc72bb7e_0
  - r-rocr=1.0_11=r43hc72bb7e_4
  - r-rprojroot=2.1.0=r43hc72bb7e_0
  - r-rspectra=0.16_2=r43h3704496_1
  - r-rtsne=0.17=r43hf1899b2_2
  - r-sass=0.4.10=r43h93ab643_0
  - r-scales=1.4.0=r43hc72bb7e_0
  - r-scattermore=1.2=r43h0d4f4ea_3
  - r-sctransform=0.4.2=r43hc2d650c_0
  - r-seurat=5.3.0=r43h93ab643_0
  - r-seuratobject=5.1.0=r43h93ab643_0
  - r-shiny=1.11.1=r43h785f33e_0
  - r-sitmo=2.0.2=r43h0d4f4ea_3
  - r-sourcetools=0.1.7_1=r43ha18555a_2
  - r-sp=2.2_0=r43h2b5f3a1_0
  - r-spam=2.11_1=r43h18dfbaa_0
  - r-spatstat.data=3.1_6=r43hc72bb7e_0
  - r-spatstat.explore=3.2_3=r43h76d94ec_0
  - r-spatstat.geom=3.2_5=r43h76d94ec_0
  - r-spatstat.random=3.1_6=r43h884c59f_0
  - r-spatstat.sparse=3.1_0=r43hdb488b9_1
  - r-spatstat.utils=3.1_5=r43h54b55ab_0
  - r-stringi=1.8.7=r43h3c328a7_0
  - r-stringr=1.5.1=r43h785f33e_1
  - r-survival=3.8_3=r43h2b5f3a1_0
  - r-sys=3.4.3=r43h2b5f3a1_0
  - r-tensor=1.5.1=r43hc72bb7e_0
  - r-tibble=3.3.0=r43h2b5f3a1_0
  - r-tidyr=1.3.1=r43h0d4f4ea_1
  - r-tidyselect=1.2.1=r43hc72bb7e_1
  - r-tinytex=0.57=r43hc72bb7e_0
  - r-utf8=1.2.6=r43h2b5f3a1_0
  - r-uwot=0.2.3=r43h93ab643_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-withr=3.0.2=r43hc72bb7e_0
  - r-xfun=0.52=r43h93ab643_0
  - r-xtable=1.8_4=r43hc72bb7e_6
  - r-yaml=2.3.10=r43hdb488b9_0
  - r-zoo=1.8_14=r43h2b5f3a1_0
  - readline=8.2=h8c095d6_2
  - sed=4.9=h6688a6e_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tzdata=2025b=h78e105d_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/daraujo/.conda/envs/seurat_env
